baseurl = "https://muryp.my.id/"
title = "MuryP Beta"
theme = "muryp3"
disqusShortname = "muryp"

[outputs]
    home = ["HTML", "RSS", "JSON", "css"]

[taxonomies]
  ide = "ide"
  tag = "tags"
  author = "authors"
  projek = "projek"

[permalinks]
  blog = "/:slug/"
  laman = "/:slug/"
  ideku = "/:slug/"
  en = "/en/:slug/"

languageCode = "id-id"
DefaultContentLanguage = "id"
paginate = 10

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[params]
  kataku = "I'm MuryP. I'm from Indonesian.<br/>I'm focus on Front End now. But I like Drawing, writing, and analyzed."
  github = "https://github.com/alifmuryp"
  gitlab = "https://gitlab.com/muryp"
  facebook = "https://facebook.com/alifmuryp"
  sitename = "MuryP Beta"
  twitter = "@alifmuryp"
  og_image = "https://muryp.gitlab.io/image/noimg.png"
  host = "https://muryp.gitlab.io/image"
  img = "https://muryp.gitlab.io/image/authors/muryp.png"
  thumb = "https://muryp.gitlab.io/image/authors/muryp.min.png"
  icon = "https://muryp.gitlab.io/image/muryp/favicon.ico"
  bagianAtas = "https://muryp.gitlab.io/image/bg.png"
    # Site Author
    author = "MuryP"
    # Description/subtitle for homepage
    description = "MuryP, MuryP Beta, Internet, Technology, hardware, Operating Sistem, Software, Jaringan Komunikasi, JarKom, TIK, Ringkasan, Alief Prihantoro, Alif MuryP, Buku, Ebook,My Project Drawing/Desain,UI/UX,front end,Blogging, SEO,catatan"
    # Color
    color = "#333" # warna bassic
    tebal = "color:#000;" #bold
    warna2 = "#00008b" # warna very dark
    # Background Color
    bgbody = "#eaeaea"
    muda = "#00008b80"       # -----warna muda
    nav1 = "#00008bcc" # warna darkblue (.8)
    nav2 = "#ebebeb"
    bayangan = "#00000033"
    
    # Font 
    font1 = "sans-serif"
    
    

pygmentsUseClasses=true

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

[menu]
  [[menu.main]]
    identifier = "Home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "About"
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    identifier = "Kontak"
    name = "Kontak"
    url = "/contact/"
    weight = 3
  [[menu.main]]
    identifier = "Catatan"
    name = "Catatan"
    url = "/note/"
    weight = 4
  [[menu.main]]
    identifier = "Bookmark"
    name = "Bookmark"
    url = "/bookmark"
    weight = 5
  [[menu.main]]
    identifier = "Kumpulan Ide"
    name = "Kumpulan Ide"
    url = "/ideku/"
    weight = 6
    # sosmed -------------
  [[menu.sosmed]]
    identifier = "github"
    name = "github"
    url = "https://github.com/alifmuryp"
    weight = 1
  [[menu.sosmed]]
    identifier = "linkedin"
    name = "linkedin"
    url = "https://www.linkedin.com/in/alifmuryp"
    weight = 2
  [[menu.sosmed]]
    identifier = "instagram"
    name = "instagram"
    url = "https://www.instagram.com/murypstudio/"
    weight = 3
  [[menu.sosmed]]
    identifier = "twitter"
    name = "twitter"
    url = "https://twitter.com/murypstudio"
    weight = 4
  [[menu.sosmed]]
    identifier = "facebook"
    name = "facebook"
    url = "https://facebook.com/murypstudio"
    weight = 5
  [[menu.sosmed]]
    identifier = "pinteres"
    name = "pinteres"
    url = "https://pinterest.com/alifmuryp/"
    weight = 6
  [[menu.sosmed]]
    identifier = "deviantart"
    name = "deviantart"
    url = "https://www.deviantart.com/alifmuryp"
    weight = 7
  [[menu.sosmed]]
    identifier = "behance"
    name = "behance"
    url = "https://www.behance.net/muryp"
    weight = 8
  [[menu.sosmed]]
    identifier = "drible"
    name = "drible"
    url = "https://www.dribbble.com/murypstudio"
    weight = 8
    # contact me
  [[menu.contact]]
    identifier = "telegram"
    name = "telegram"
    url = "https://t.me/muryp"
    weight = 1
  [[menu.contact]]
    identifier = "gmail"
    name = "gmail"
    url = "mailto:alifmuryp@gmail.com"
    weight = 2
   # Ask me
  [[menu.ask]]
    identifier = "twitter"
    name = "twitter"
    url = "https://twitter.com/murypstudio"
    weight = 1
  [[menu.ask]]
    identifier = "facebook"
    name = "facebook"
    url = "https://facebook.com/murypstudio"
    weight = 2